# Generated by Django 4.1.5 on 2023-01-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume_en',
            field=models.FileField(default='cv.pdf', upload_to='', verbose_name='resume english'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 6, 16, 0, 247726, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
