# Generated by Django 4.1.5 on 2023-01-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutme_facebook_aboutme_instagram_aboutme_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description_en',
            field=models.CharField(default='a', max_length=250, verbose_name='description english'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=64, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name_en',
            field=models.CharField(max_length=64, verbose_name='company name in english'),
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 7, 43, 38, 531264, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
