# Generated by Django 4.1.5 on 2023-01-19 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_photogallery_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='title',
            field=models.CharField(default='title', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 38, 40, 717007, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
