# Generated by Django 4.1.5 on 2023-01-19 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_photogallery_title_en_alter_startproject_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='size',
            field=models.CharField(choices=[('col-lg-8', 'Big'), ('col-lg-4 col-sm-6', 'Small')], default='col-lg-4 col-sm-6', max_length=34, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 46, 17, 214521, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
