# Generated by Django 4.1.5 on 2023-01-19 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_photogallery_size_alter_startproject_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(help_text='recommended: Image(856X416) OR Image(416X416)', upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 10, 9, 186053, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
