# Generated by Django 4.1.5 on 2023-01-19 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contact_modified_alter_startproject_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='facebook',
            field=models.CharField(default='#', max_length=150, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='instagram',
            field=models.CharField(default='#', max_length=150, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='linkedin',
            field=models.CharField(default='#', max_length=150, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='skype',
            field=models.CharField(default='#', max_length=150, verbose_name='skype'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='twitter',
            field=models.CharField(default='#', max_length=150, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 40, 50, 947500, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
