# Generated by Django 4.1.5 on 2023-01-19 01:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutme_facebook_alter_aboutme_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 58, 29, 312592, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sample', to='core.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='title_en',
            field=models.CharField(max_length=64, verbose_name='title english'),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='website_url',
            field=models.CharField(default='#', max_length=250, verbose_name='website url'),
        ),
    ]
