# Generated by Django 4.1.5 on 2023-01-19 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clientsayaboutme_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_tag',
            field=models.CharField(default='web', max_length=68, verbose_name='filter tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 2, 25, 30, 650216, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
