# Generated by Django 4.1.5 on 2023-01-19 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_category_filter_tag_alter_startproject_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='end_at_en',
            field=models.CharField(default='15/12/2021', max_length=34, verbose_name='end at english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='start_at_en',
            field=models.CharField(default='05/12/2021', max_length=34, verbose_name='start at english'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 2, 33, 11, 389254, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
