# Generated by Django 4.1.5 on 2023-01-19 05:08

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_worksamples_end_at_en_worksamples_start_at_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEn',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.project',),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='startproject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 5, 8, 40, 224920, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
