# Generated by Django 4.1.5 on 2023-01-18 05:37

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('title_en', models.CharField(max_length=120, verbose_name='title english')),
                ('author', models.CharField(max_length=34, verbose_name='author')),
                ('author_en', models.CharField(max_length=34, verbose_name='author')),
                ('image_cover', models.ImageField(help_text='recommended: Image(420X260)', upload_to='', verbose_name='image cover')),
                ('image', models.ImageField(help_text='recommended: Image(750X450)', upload_to='', verbose_name='image')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 5, 37, 16, 542990, tzinfo=datetime.timezone.utc), verbose_name='date')),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('body_en', ckeditor.fields.RichTextField(verbose_name='body english')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
