# Generated by Django 4.1.5 on 2023-01-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 6, 16, 0, 251617, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
