# Generated by Django 4.1.5 on 2023-01-18 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 6, 37, 41, 730050, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
