# Generated by Django 4.1.5 on 2023-01-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 7, 43, 38, 534686, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
