# Generated by Django 4.1.5 on 2023-01-19 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Newsletter Subscribe',
                'verbose_name_plural': 'Newsletters Subscribes',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 5, 8, 40, 229848, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
